services:
  database:
    image: postgres:17-alpine
    restart: always
    environment:
       POSTGRES_USER: meyou
       POSTGRES_PASSWORD: 5534326t
       POSTGRES_DB: riddle_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meyou -d riddle_db"]
      interval: 8s
      timeout: 8s
      retries: 5
      start_period: 30s
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://meyou:5534326t@database:5432/riddle_db?schema=public"
    depends_on:
      database:
        condition: service_healthy
    
  frontend:
    build: ./frontend
    ports:
      - "5201:5201"
    depends_on:
      - backend

volumes:
  postgres_data: